import {
  OrderStatus,
  PaperType,
  ProductType,
  ServiceType,
  FilamentType,
  ResinType,
  SupplyType,
} from '../common/enums';
import { StoreState } from './store.state';
import { Product, Order } from '../common/interfaces';
import { createDefaultMachineProfiles } from '../settings/machine-profile.util';
import { inferSupplyCategory } from '../supplies/supply-category.util';
import { ensureOrderStatusHistory } from '../orders/order-status-history.util';

export function createEmptyState(): StoreState {
  return {
    generalSettings: {
      electricityCostPerKwh: 0,
      powerConsumptions: [],
      machineCosts: [],
      machineProfiles: createDefaultMachineProfiles(),
      laborCostPerHour: 0,
      profitMargins: {
        impresion_3d: 40,
        diseno: 50,
        estampado: 35,
      },
      paperPricesPerSqm: {
        sublimacion: 0,
        dtf: 0,
        dtfUv: 0,
      },
      filamentPrices: [],
      resinPrices: [],
      errorMarginPercent: 0,
      filamentTypeAverages: {},
      resinTypeAverages: {},
    },
    supplies: [],
    impresos: [],
    categories: [],
    products: [],
    customers: [],
    orders: [],
    printJobs: [],
    retailSales: [],
    materials: [],
  };
}

export function createSeedState(): StoreState {
  const generalSettings = {
    electricityCostPerKwh: 85,
    powerConsumptions: [
      { id: 'pw-1', name: 'Impresora FDM', watts: 120 },
      { id: 'pw-2', name: 'Impresora Resina', watts: 60 },
      { id: 'pw-3', name: 'Prensa estampado', watts: 350 },
    ],
    machineCosts: [
      { id: 'mc-1', name: 'Impresora FDM', costPerHour: 150 },
      { id: 'mc-2', name: 'Impresora Resina', costPerHour: 200 },
    ],
    machineProfiles: createDefaultMachineProfiles().map((profile) =>
      profile.id === 'mp-res-wash'
        ? { ...profile, washSupplyId: 'sup-3b' }
        : profile,
    ),
    laborCostPerHour: 800,
    profitMargins: {
      impresion_3d: 40,
      diseno: 50,
      estampado: 35,
    },
    paperPricesPerSqm: {
      sublimacion: 4500,
      dtf: 6500,
      dtfUv: 8500,
    },
    filamentPrices: [
      {
        id: 'fp-1',
        brand: 'FilAr',
        materialType: FilamentType.PLA,
        pricePerKg: 18000,
      },
      {
        id: 'fp-2',
        brand: 'FilAr',
        materialType: FilamentType.ABS,
        pricePerKg: 22000,
      },
      {
        id: 'fp-3',
        brand: 'FilAr',
        materialType: FilamentType.PETG,
        pricePerKg: 24000,
      },
      {
        id: 'fp-4',
        brand: 'Printalot',
        materialType: FilamentType.PLA,
        pricePerKg: 16500,
      },
      {
        id: 'fp-5',
        brand: 'Printalot',
        materialType: FilamentType.TPU,
        pricePerKg: 28000,
      },
    ],
    resinPrices: [
      {
        id: 'rp-1',
        brand: 'Elegoo',
        resinType: ResinType.TRANSLUCIDA,
        pricePerLiter: 35000,
      },
      {
        id: 'rp-2',
        brand: 'Elegoo',
        resinType: ResinType.DURA,
        pricePerLiter: 32000,
      },
      {
        id: 'rp-3',
        brand: 'Anycubic',
        resinType: ResinType.ESTANDAR,
        pricePerLiter: 30000,
      },
    ],
    errorMarginPercent: 5,
    filamentTypeAverages: {},
    resinTypeAverages: {},
  };

  const supplies = [
    {
      id: 'sup-1',
      name: 'Filamento PLA Negro',
      type: SupplyType.FILAMENTO,
      filamentType: FilamentType.PLA,
      brand: 'FilAr',
      unit: 'kg',
      quantity: 2.5,
      minStock: 1,
      unitPrice: 18000,
      priceFromSettings: true,
      supplier: 'FilAr 3D',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'sup-2',
      name: 'Filamento ABS Blanco',
      type: SupplyType.FILAMENTO,
      filamentType: FilamentType.ABS,
      brand: 'FilAr',
      unit: 'kg',
      quantity: 0.8,
      minStock: 1,
      unitPrice: 22000,
      priceFromSettings: true,
      supplier: 'FilAr 3D',
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'sup-3',
      name: 'Resina translúcida',
      type: SupplyType.RESINA,
      resinType: ResinType.TRANSLUCIDA,
      brand: 'Elegoo',
      unit: 'L',
      quantity: 1.2,
      minStock: 0.5,
      unitPrice: 35000,
      priceFromSettings: true,
      supplier: 'Elegoo Store',
      updatedAt: '2026-06-15T00:00:00.000Z',
    },
    {
      id: 'sup-3b',
      name: 'Alcohol isopropílico 99%',
      type: SupplyType.ALCOHOL,
      unit: 'L',
      quantity: 2,
      minStock: 0.5,
      unitPrice: 4500,
      priceFromSettings: false,
      supplier: 'Química local',
      updatedAt: '2026-06-15T00:00:00.000Z',
    },
    {
      id: 'sup-4',
      name: 'Tinta DTF CMYK',
      type: SupplyType.TINTA,
      unit: 'ml',
      quantity: 500,
      minStock: 200,
      unitPrice: 12,
      priceFromSettings: false,
      supplier: 'Textil Ink',
      updatedAt: '2026-06-20T00:00:00.000Z',
    },
    {
      id: 'sup-5',
      name: 'Remeras algodón 180g',
      type: SupplyType.REMERA,
      unit: 'unidad',
      quantity: 45,
      minStock: 20,
      unitPrice: 3500,
      priceFromSettings: false,
      supplier: 'Textil Mayorista',
      updatedAt: '2026-07-03T00:00:00.000Z',
    },
    {
      id: 'sup-6',
      name: 'Tazas cerámica blanca',
      type: SupplyType.TAZA,
      unit: 'unidad',
      quantity: 30,
      minStock: 10,
      unitPrice: 2800,
      priceFromSettings: false,
      supplier: 'Sublimación AR',
      updatedAt: '2026-06-28T00:00:00.000Z',
    },
  ];

  const impresos = [
    {
      id: 'imp-1',
      name: 'Logo',
      paperType: PaperType.DTF,
      widthCm: 10,
      heightCm: 10,
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'imp-2',
      name: 'Estampa 25×25',
      paperType: PaperType.DTF,
      widthCm: 25,
      heightCm: 25,
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'imp-3',
      name: 'Estampa 40×30',
      paperType: PaperType.DTF,
      widthCm: 40,
      heightCm: 30,
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'imp-4',
      name: 'Full A4 sublimación',
      paperType: PaperType.SUBLIMACION,
      widthCm: 21,
      heightCm: 29.7,
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
    {
      id: 'imp-5',
      name: 'Etiqueta DTF UV',
      paperType: PaperType.DTF_UV,
      widthCm: 8,
      heightCm: 8,
      updatedAt: '2026-07-01T00:00:00.000Z',
    },
  ];

  const categories = [
    {
      id: 'cat-1',
      name: 'Figuras',
      productTypes: [ProductType.FDM, ProductType.RESINA],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-2',
      name: 'Llaveros',
      productTypes: [ProductType.FDM, ProductType.RESINA],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-3',
      name: 'Prototipos',
      productTypes: [ProductType.FDM, ProductType.RESINA],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-4',
      name: 'Repuestos',
      productTypes: [ProductType.FDM, ProductType.RESINA],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-5',
      name: 'Decoración',
      productTypes: [ProductType.FDM, ProductType.RESINA],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-6',
      name: 'Remeras',
      productTypes: [ProductType.ESTAMPADO],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-7',
      name: 'Buzos',
      productTypes: [ProductType.ESTAMPADO],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-8',
      name: 'Gorras',
      productTypes: [ProductType.ESTAMPADO],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-9',
      name: 'Tazas',
      productTypes: [ProductType.ESTAMPADO],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'cat-10',
      name: 'Bolsas',
      productTypes: [ProductType.ESTAMPADO],
      createdAt: '2026-01-01T00:00:00.000Z',
    },
  ];

  const products = [
    {
      id: 'prod-1',
      name: 'Figura personalizada PLA',
      images: [],
      updatedAt: '2026-07-01T11:00:00.000Z',
      price: 8500,
      cost: 3200,
      profit: 5300,
      categoryIds: ['cat-1'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '12 × 8 × 5 cm',
      grams: 45,
      printTimeHours: 3.5,
      workTimeHours: 0.5,
      brand: 'FilAr',
      filamentType: FilamentType.PLA,
    },
    {
      id: 'prod-2',
      name: 'Prototipo funcional ABS',
      images: [],
      updatedAt: '2026-07-05T09:30:00.000Z',
      price: 12000,
      cost: 4800,
      profit: 7200,
      categoryIds: ['cat-3'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '15 × 10 × 6 cm',
      grams: 80,
      printTimeHours: 5,
      workTimeHours: 1,
      brand: 'FilAr',
      filamentType: FilamentType.ABS,
    },
    {
      id: 'prod-3',
      name: 'Miniatura resina',
      images: [],
      updatedAt: '2026-06-20T14:00:00.000Z',
      price: 4500,
      cost: 1500,
      profit: 3000,
      categoryIds: ['cat-1'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.RESINA,
      size: '8 × 5 × 4 cm',
      grams: 25,
      printTimeHours: 2,
      workTimeHours: 1.5,
      brand: 'Elegoo',
      resinType: ResinType.TRANSLUCIDA,
    },
    {
      id: 'prod-4',
      name: 'Remera estampada DTF',
      images: [],
      updatedAt: '2026-06-28T15:00:00.000Z',
      price: 6500,
      cost: 2800,
      profit: 3700,
      categoryIds: ['cat-6'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.ESTAMPADO,
      size: '20 × 25 cm',
    },
    {
      id: 'prod-5',
      name: 'Buzo con estampado vinílico',
      images: [],
      updatedAt: '2026-07-03T10:00:00.000Z',
      price: 9800,
      cost: 4200,
      profit: 5600,
      categoryIds: ['cat-7'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.ESTAMPADO,
      size: 'A4',
    },
    {
      id: 'prod-6',
      name: 'Llavero corporativo 3D',
      images: [],
      updatedAt: '2026-06-15T08:00:00.000Z',
      price: 1200,
      cost: 350,
      profit: 850,
      categoryIds: ['cat-2'],
      published: true,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '4 × 2 × 0.5 cm',
      grams: 8,
      printTimeHours: 0.4,
      workTimeHours: 0.1,
      brand: 'Printalot',
      filamentType: FilamentType.PLA,
    },
    {
      id: 'prod-7',
      name: 'Base árbol de equilibrio',
      images: [],
      updatedAt: '2026-07-08T10:00:00.000Z',
      price: 4500,
      cost: 1800,
      profit: 2700,
      categoryIds: ['cat-4'],
      published: false,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '10 × 10 × 3 cm',
      grams: 55,
      printTimeHours: 4,
      workTimeHours: 0.5,
      filamentType: FilamentType.PLA,
    },
    {
      id: 'prod-8',
      name: 'Tablero árbol de equilibrio',
      images: [],
      updatedAt: '2026-07-08T10:00:00.000Z',
      price: 3200,
      cost: 1200,
      profit: 2000,
      categoryIds: ['cat-4'],
      published: false,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '18 × 18 × 0.8 cm',
      grams: 35,
      printTimeHours: 2.5,
      workTimeHours: 0.3,
      filamentType: FilamentType.PLA,
    },
    {
      id: 'prod-9',
      name: 'Pieza de juego (árbol)',
      images: [],
      updatedAt: '2026-07-08T10:00:00.000Z',
      price: 180,
      cost: 45,
      profit: 135,
      categoryIds: ['cat-4'],
      published: false,
      components: [],
      assemblyTimeHours: 0,
      type: ProductType.FDM,
      size: '3 × 2 × 1 cm',
      grams: 4,
      printTimeHours: 0.25,
      workTimeHours: 0.05,
      filamentType: FilamentType.PLA,
    },
    {
      id: 'prod-10',
      name: 'Árbol de equilibrio (completo)',
      images: [],
      updatedAt: '2026-07-09T12:00:00.000Z',
      price: 14500,
      cost: 5220,
      profit: 9280,
      categoryIds: ['cat-4'],
      published: true,
      components: [
        { productId: 'prod-7', quantity: 1 },
        { productId: 'prod-8', quantity: 1 },
        { productId: 'prod-9', quantity: 28 },
      ],
      assemblyTimeHours: 1,
      type: ProductType.FDM,
      size: '18 × 18 × 25 cm',
      grams: 0,
      printTimeHours: 0,
      workTimeHours: 0,
      filamentType: FilamentType.PLA,
    },
  ];

  const customers = [
    {
      id: 'cust-1',
      name: 'María González',
      email: 'maria@disenocreativo.com',
      phone: '+54 11 4567-8901',
      company: 'Diseño Creativo SA',
      createdAt: '2026-01-15T10:00:00.000Z',
    },
    {
      id: 'cust-2',
      name: 'Carlos Ruiz',
      email: 'carlos@tallermsur.com',
      phone: '+54 11 2345-6789',
      company: 'Taller Mecánico Sur',
      createdAt: '2026-02-03T14:30:00.000Z',
    },
    {
      id: 'cust-3',
      name: 'Lucía Fernández',
      email: 'lucia.f@gmail.com',
      phone: '+54 11 9876-5432',
      createdAt: '2026-03-10T09:15:00.000Z',
    },
    {
      id: 'cust-4',
      name: 'Emprendimientos Norte',
      email: 'contacto@empnorte.com',
      phone: '+54 351 555-0100',
      company: 'Emprendimientos Norte',
      createdAt: '2026-04-22T16:45:00.000Z',
    },
  ];

  const orders: Order[] = [
    {
      id: 'ord-1',
      customerId: 'cust-1',
      customerName: 'María González',
      services: [ServiceType.IMPRESION_3D],
      items: [
        {
          serviceType: ServiceType.IMPRESION_3D,
          productId: 'prod-1',
          productName: 'Figura personalizada PLA',
          quantity: 2,
          unitPrice: 8500,
        },
      ],
      status: OrderStatus.EN_PRODUCCION,
      total: 17000,
      description: 'Figuras personalizadas en PLA rojo mate',
      notes: 'Color rojo, acabado mate',
      createdAt: '2026-07-01T11:00:00.000Z',
      dueDate: '2026-07-12T18:00:00.000Z',
    },
    {
      id: 'ord-6',
      customerId: 'cust-1',
      customerName: 'María González',
      services: [ServiceType.ESTAMPADO],
      items: [
        {
          serviceType: ServiceType.ESTAMPADO,
          productId: 'prod-3',
          productName: 'Remera estampada DTF',
          quantity: 10,
          unitPrice: 6500,
        },
      ],
      status: OrderStatus.ENTREGADO,
      total: 65000,
      description: 'Remeras corporativas DTF',
      notes: 'Pedido corporativo entregado',
      createdAt: '2026-05-10T10:00:00.000Z',
      dueDate: '2026-05-25T18:00:00.000Z',
    },
    {
      id: 'ord-2',
      customerId: 'cust-2',
      customerName: 'Carlos Ruiz',
      services: [ServiceType.IMPRESION_3D],
      items: [
        {
          serviceType: ServiceType.IMPRESION_3D,
          productId: 'prod-2',
          productName: 'Prototipo funcional ABS',
          quantity: 1,
          unitPrice: 12000,
        },
      ],
      status: OrderStatus.PENDIENTE,
      total: 12000,
      description: 'Prototipo funcional en ABS',
      createdAt: '2026-07-05T09:30:00.000Z',
      dueDate: '2026-07-15T18:00:00.000Z',
    },
    {
      id: 'ord-3',
      customerId: 'cust-3',
      customerName: 'Lucía Fernández',
      services: [ServiceType.ESTAMPADO],
      items: [
        {
          serviceType: ServiceType.ESTAMPADO,
          productId: 'prod-3',
          productName: 'Remera estampada DTF',
          quantity: 5,
          unitPrice: 6500,
        },
      ],
      status: OrderStatus.COMPLETADO,
      total: 32500,
      description: 'Remeras estampadas surtidas',
      notes: 'Talles: 2M, 2L, 1XL',
      createdAt: '2026-06-28T15:00:00.000Z',
      dueDate: '2026-07-08T18:00:00.000Z',
    },
    {
      id: 'ord-4',
      customerId: 'cust-4',
      customerName: 'Emprendimientos Norte',
      services: [ServiceType.ESTAMPADO, ServiceType.DISENO],
      items: [
        {
          serviceType: ServiceType.DISENO,
          productName: 'Diseño de logo corporativo',
          quantity: 1,
          unitPrice: 15000,
        },
        {
          serviceType: ServiceType.ESTAMPADO,
          productId: 'prod-4',
          productName: 'Buzo con estampado vinílico',
          quantity: 20,
          unitPrice: 9800,
        },
      ],
      status: OrderStatus.EN_PRODUCCION,
      total: 211000,
      description: 'Buzos con logo corporativo',
      notes: 'Logo en pecho y espalda',
      createdAt: '2026-07-03T10:00:00.000Z',
      dueDate: '2026-07-20T18:00:00.000Z',
    },
    {
      id: 'ord-5',
      customerId: 'cust-4',
      customerName: 'Emprendimientos Norte',
      services: [ServiceType.IMPRESION_3D],
      items: [
        {
          serviceType: ServiceType.IMPRESION_3D,
          productId: 'prod-5',
          productName: 'Llavero corporativo 3D',
          quantity: 100,
          unitPrice: 1200,
        },
      ],
      status: OrderStatus.ENTREGADO,
      total: 120000,
      description: 'Llaveros corporativos 3D',
      createdAt: '2026-06-15T08:00:00.000Z',
      dueDate: '2026-06-25T18:00:00.000Z',
    },
    {
      id: 'ord-7',
      customerId: 'cust-1',
      customerName: 'María González',
      services: [
        ServiceType.DISENO,
        ServiceType.IMPRESION_3D,
        ServiceType.ESTAMPADO,
      ],
      items: [
        {
          serviceType: ServiceType.DISENO,
          productName: 'Modelado 3D y arte vectorial',
          quantity: 1,
          unitPrice: 22000,
        },
        {
          serviceType: ServiceType.IMPRESION_3D,
          productId: 'prod-1',
          productName: 'Figura personalizada PLA',
          quantity: 1,
          unitPrice: 8500,
        },
        {
          serviceType: ServiceType.ESTAMPADO,
          productId: 'prod-3',
          productName: 'Remera estampada DTF',
          quantity: 3,
          unitPrice: 6500,
        },
      ],
      status: OrderStatus.PENDIENTE,
      total: 50000,
      description: 'Proyecto integral: diseño, pieza 3D y remeras estampadas',
      createdAt: '2026-07-09T12:00:00.000Z',
      dueDate: '2026-07-25T18:00:00.000Z',
    },
  ];

  const printJobs: StoreState['printJobs'] = [];

  const retailSales = [
    {
      id: 'sale-1',
      items: [
        {
          productId: 'prod-1',
          productName: 'Figura personalizada PLA',
          quantity: 1,
          unitPrice: 8500,
          lineTotal: 8500,
        },
      ],
      total: 8500,
      notes: 'Venta en mostrador',
      soldAt: '2026-07-08T16:30:00.000Z',
      createdAt: '2026-07-08T16:30:00.000Z',
    },
    {
      id: 'sale-2',
      items: [
        {
          productId: 'prod-9',
          productName: 'Pieza de juego (árbol)',
          quantity: 3,
          unitPrice: 180,
          lineTotal: 540,
        },
        {
          productId: 'prod-8',
          productName: 'Tablero árbol de equilibrio',
          quantity: 1,
          unitPrice: 3200,
          lineTotal: 3200,
        },
      ],
      total: 3740,
      soldAt: '2026-07-09T11:15:00.000Z',
      createdAt: '2026-07-09T11:15:00.000Z',
    },
  ];

  const materials = [
    {
      id: 'mat-1',
      name: 'Filamento PLA Negro',
      type: ServiceType.IMPRESION_3D,
      quantity: 2.5,
      unit: 'kg',
      minStock: 1,
      supplier: 'FilAr 3D',
    },
    {
      id: 'mat-2',
      name: 'Filamento ABS Blanco',
      type: ServiceType.IMPRESION_3D,
      quantity: 0.8,
      unit: 'kg',
      minStock: 1,
      supplier: 'FilAr 3D',
    },
    {
      id: 'mat-3',
      name: 'Tinta DTF CMYK',
      type: ServiceType.ESTAMPADO,
      quantity: 500,
      unit: 'ml',
      minStock: 200,
      supplier: 'Textil Ink',
    },
    {
      id: 'mat-4',
      name: 'Film DTF A3',
      type: ServiceType.ESTAMPADO,
      quantity: 45,
      unit: 'hojas',
      minStock: 20,
      supplier: 'Textil Ink',
    },
    {
      id: 'mat-5',
      name: 'Vinilo textil blanco',
      type: ServiceType.ESTAMPADO,
      quantity: 8,
      unit: 'm',
      minStock: 5,
      supplier: 'Vinilos Pro',
    },
  ];

  const ord1 = orders.find((order) => order.id === 'ord-1');
  if (ord1) {
    ord1.statusHistory = [
      {
        id: 'ord-1-hist-1',
        fromStatus: null,
        toStatus: OrderStatus.PENDIENTE,
        changedAt: '2026-07-01T11:00:00.000Z',
        source: 'manual',
      },
      {
        id: 'ord-1-hist-2',
        fromStatus: OrderStatus.PENDIENTE,
        toStatus: OrderStatus.EN_PRODUCCION,
        changedAt: '2026-07-03T14:20:00.000Z',
        source: 'auto',
      },
    ];
  }

  for (const order of orders) {
    if (!order.statusHistory?.length) {
      ensureOrderStatusHistory(order);
    }
  }

  return {
    generalSettings,
    supplies: supplies.map((supply) => ({
      ...supply,
      category: inferSupplyCategory(supply.type),
    })),
    impresos,
    categories,
    products: products.map((product) => ({
      ...product,
      includesPieces:
        product.type === ProductType.COMBO ||
        (product.components?.length ?? 0) > 0,
    })) as Product[],
    customers,
    orders,
    printJobs,
    retailSales,
    materials,
  };
}
